Preprocessing Script for cropped watermarks
EvgheniiBeriozchin/watermark-detection pull request #19
Opened 2023-06-13 11:08 UTC by PauliJulia

2023-06-13 20:06 UTC, SebastianP1997 submitted a review, later dismissed

2023-06-15 07:29 UTC, EvgheniiBeriozchin requested changes
Could you remove all comments (unless they are block comments at the beginning of the function), especially commented out code? The current standard is to avoid (many) comments as they more clutter the code, instead of helping. Usually function and variable names  (should be enough to) explain what the code does.
Also the load images function + all the code below it, are not necessary for the pipeline, so you can remove them.

2023-06-15 07:49 UTC, PauliJulia commented
Code is changed - please check again.

2023-06-15 08:01 UTC, EvgheniiBeriozchin commented
The imshow function is also unused now, but you can remove this in a separate PR (or I can do it as well when I'll push the restructuring code). Thanks for modifying

2023-06-15 08:01 UTC, EvgheniiBeriozchin approved these changes

2023-06-16 10:23 UTC, SebastianP1997 approved these changes

2023-06-16 10:25 UTC, merged